import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import {cn} from '@/lib/utils'
import Navbar from '@/components/navbar/navbar'
import Footer from '@/components/footer/footer'
import { Toaster } from "@/components/ui/toaster"
import Link from "next/link";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) 
   
{

  return (
    <html lang="en" className='h-full'>
      <body
        className={cn('relative h-full font-sans antialiased',geistSans.variable, geistMono.variable)}>

        <main className="relative flex flex-col min-h-screen">
        
     
        <Navbar />

       
        <div className='flex-grow flex-1' >
         
          <Link id='test' href='/contact' className='hidden' ></Link>
         
        
          {children}
          <Toaster />
        </div>
        
       <Footer />
      </main>
      
      </body>
    </html>
  );
}
